import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideIcons } from '@ng-icons/core';
import {
  phosphorPlusFill,
  phosphorCheckFill,
  phosphorXFill,
  phosphorWarningFill,
  phosphorInfoFill,
  phosphorStarFill,
  phosphorHeartFill,
  phosphorTrophyFill,
  phosphorGiftFill,
  phosphorCoinsFill,
  phosphorUserFill,
  phosphorLockFill,
  phosphorCaretRightFill,
  phosphorSealCheckFill,
  phosphorHouseFill,
  phosphorBellFill,
  phosphorPlayFill,
  phosphorMagnifyingGlassFill,
  phosphorCardsFill,
  phosphorStackFill,
  phosphorArrowsLeftRightFill,
  phosphorQrCodeFill,
  phosphorTicketFill,
  phosphorStorefrontFill,
  phosphorCaretDownFill,
  phosphorHashFill,
  phosphorSparkleFill,
  phosphorArrowRightFill,
} from '@ng-icons/phosphor-icons/fill';
import {
  heroPlusSolid,
  heroCheckSolid,
  heroXMarkSolid,
  heroExclamationTriangleSolid,
  heroInformationCircleSolid,
  heroStarSolid,
  heroHeartSolid,
  heroTrophySolid,
  heroGiftSolid,
  heroUserSolid,
  heroLockClosedSolid,
  heroBoltSolid,
  heroChevronRightSolid,
  heroSparklesSolid,
} from '@ng-icons/heroicons/solid';
import { routes } from './app.routes';
import { authInterceptor } from './interceptores/auth.interceptor';

//test
export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    ...provideIcons({
      phosphorPlusFill,
      phosphorCheckFill,
      phosphorXFill,
      phosphorWarningFill,
      phosphorInfoFill,
      phosphorStarFill,
      phosphorHeartFill,
      phosphorTrophyFill,
      phosphorGiftFill,
      phosphorCoinsFill,
      phosphorUserFill,
      phosphorLockFill,
      phosphorCaretRightFill,
      phosphorSealCheckFill,
      phosphorHouseFill,
      phosphorBellFill,
      phosphorPlayFill,
      phosphorMagnifyingGlassFill,
      phosphorCardsFill,
      phosphorStackFill,
      phosphorArrowsLeftRightFill,
      phosphorQrCodeFill,
      phosphorTicketFill,
      phosphorStorefrontFill,
      phosphorCaretDownFill,
      phosphorHashFill,
      phosphorSparkleFill,
      phosphorArrowRightFill,
      heroPlusSolid,
      heroCheckSolid,
      heroXMarkSolid,
      heroExclamationTriangleSolid,
      heroInformationCircleSolid,
      heroStarSolid,
      heroHeartSolid,
      heroTrophySolid,
      heroGiftSolid,
      heroUserSolid,
      heroLockClosedSolid,
      heroBoltSolid,
      heroChevronRightSolid,
      heroSparklesSolid,
    }),
  ],
};
