// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPI2026.Infraestructura.Data;

#nullable disable

namespace TPI2026.Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921014948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TPI2026.Dominio.Entidades.AperturaSobre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SobreId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SobreId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("aperturasobre", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.AperturaSobreCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AperturaSobreId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AperturaSobreId");

                    b.HasIndex("CartaId");

                    b.ToTable("aperturasobrecarta", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CostoMana")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Poder")
                        .HasColumnType("int");

                    b.Property<string>("Rareza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("carta", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.CartaPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("JugadorPartidaId")
                        .HasColumnType("int");

                    b.Property<int?>("PosicionMazo")
                        .HasColumnType("int");

                    b.Property<int?>("RondaId")
                        .HasColumnType("int");

                    b.Property<int?>("ZonaPartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaId");

                    b.HasIndex("JugadorPartidaId");

                    b.HasIndex("RondaId");

                    b.HasIndex("ZonaPartidaId");

                    b.ToTable("cartapartida", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Coleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("coleccion", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ColeccionCarta", b =>
                {
                    b.Property<int>("ColeccionId")
                        .HasColumnType("int");

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.HasKey("ColeccionId", "CartaId");

                    b.HasIndex("CartaId");

                    b.ToTable("coleccioncarta", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Cupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ColeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ColeccionId");

                    b.ToTable("cupon", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaObjetivoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaId")
                        .IsUnique();

                    b.HasIndex("CategoriaObjetivoId");

                    b.ToTable("habilidad", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Intercambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioOfertanteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioOfertanteId");

                    b.HasIndex("UsuarioReceptorId");

                    b.ToTable("intercambio", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.IntercambioCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.Property<int>("IntercambioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaId");

                    b.HasIndex("IntercambioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("intercambiocarta", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.IntercambioMoneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IntercambioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntercambioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("intercambiomoneda", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.JugadorPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManaActual")
                        .HasColumnType("int");

                    b.Property<int>("MazoId")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MazoId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("jugadorpartida", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Matchmaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MazoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MazoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("matchmaking", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Mazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mazo", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.MazoCarta", b =>
                {
                    b.Property<int>("MazoId")
                        .HasColumnType("int");

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.HasKey("MazoId", "CartaId");

                    b.HasIndex("CartaId");

                    b.ToTable("mazocarta", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GanadorId");

                    b.ToTable("partida", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ResultadoZona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanioJugador1")
                        .HasColumnType("int");

                    b.Property<int>("DanioJugador2")
                        .HasColumnType("int");

                    b.Property<int>("PoderJugador1")
                        .HasColumnType("int");

                    b.Property<int>("PoderJugador2")
                        .HasColumnType("int");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaPartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaPartidaId");

                    b.HasIndex("RondaId", "ZonaPartidaId")
                        .IsUnique();

                    b.ToTable("resultadozona", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Ronda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId", "Numero")
                        .IsUnique();

                    b.ToTable("ronda", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Sobre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadCartas")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("ColeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ColeccionId");

                    b.ToTable("sobre", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MonedasIntercambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Oro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.UsuarioCarta", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CartaId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "CartaId");

                    b.HasIndex("CartaId");

                    b.ToTable("usuariocarta", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.UsuarioCupon", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CuponId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId", "CuponId");

                    b.HasIndex("CuponId");

                    b.ToTable("usuariocupon", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("zona", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaCategoria", b =>
                {
                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("BonusPoder")
                        .HasColumnType("int");

                    b.HasKey("ZonaId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("zonacategoria", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<string>("PosicionInicial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.HasIndex("PartidaId", "ZonaId")
                        .IsUnique();

                    b.ToTable("zonapartida", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaRonda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RondaId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaPartidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaPartidaId");

                    b.HasIndex("RondaId", "ZonaPartidaId")
                        .IsUnique();

                    b.ToTable("zonaronda", (string)null);
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.AperturaSobre", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Sobre", "Sobre")
                        .WithMany("Aperturas")
                        .HasForeignKey("SobreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sobre");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.AperturaSobreCarta", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.AperturaSobre", "AperturaSobre")
                        .WithMany("Cartas")
                        .HasForeignKey("AperturaSobreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithMany("Aperturas")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AperturaSobre");

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Carta", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Cartas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.CartaPartida", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithMany("CartasPartida")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.JugadorPartida", "JugadorPartida")
                        .WithMany("Cartas")
                        .HasForeignKey("JugadorPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Ronda", "Ronda")
                        .WithMany("Cartas")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TPI2026.Dominio.Entidades.ZonaPartida", "ZonaPartida")
                        .WithMany("Cartas")
                        .HasForeignKey("ZonaPartidaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carta");

                    b.Navigation("JugadorPartida");

                    b.Navigation("Ronda");

                    b.Navigation("ZonaPartida");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ColeccionCarta", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithMany("Colecciones")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Coleccion", "Coleccion")
                        .WithMany("Cartas")
                        .HasForeignKey("ColeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Coleccion");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Cupon", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Coleccion", "Coleccion")
                        .WithMany("Cupones")
                        .HasForeignKey("ColeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coleccion");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Habilidad", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithOne("Habilidad")
                        .HasForeignKey("TPI2026.Dominio.Entidades.Habilidad", "CartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Categoria", "CategoriaObjetivo")
                        .WithMany("Habilidades")
                        .HasForeignKey("CategoriaObjetivoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Carta");

                    b.Navigation("CategoriaObjetivo");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Intercambio", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "UsuarioOfertante")
                        .WithMany()
                        .HasForeignKey("UsuarioOfertanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "UsuarioReceptor")
                        .WithMany()
                        .HasForeignKey("UsuarioReceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioOfertante");

                    b.Navigation("UsuarioReceptor");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.IntercambioCarta", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithMany()
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Intercambio", "Intercambio")
                        .WithMany("Cartas")
                        .HasForeignKey("IntercambioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Intercambio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.IntercambioMoneda", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Intercambio", "Intercambio")
                        .WithMany("Monedas")
                        .HasForeignKey("IntercambioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intercambio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.JugadorPartida", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Mazo", "Mazo")
                        .WithMany("Partidas")
                        .HasForeignKey("MazoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Partida", "Partida")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Partidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mazo");

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Matchmaking", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Mazo", "Mazo")
                        .WithMany("Matchmakings")
                        .HasForeignKey("MazoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Matchmakings")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mazo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Mazo", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Mazos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.MazoCarta", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithMany("Mazos")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Mazo", "Mazo")
                        .WithMany("Cartas")
                        .HasForeignKey("MazoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Mazo");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Partida", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ganador");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ResultadoZona", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Ronda", "Ronda")
                        .WithMany("Resultados")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.ZonaPartida", "ZonaPartida")
                        .WithMany("Resultados")
                        .HasForeignKey("ZonaPartidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ronda");

                    b.Navigation("ZonaPartida");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Ronda", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Partida", "Partida")
                        .WithMany("Rondas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Sobre", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TPI2026.Dominio.Entidades.Coleccion", "Coleccion")
                        .WithMany()
                        .HasForeignKey("ColeccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Coleccion");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.UsuarioCarta", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Carta", "Carta")
                        .WithMany("Usuarios")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Cartas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.UsuarioCupon", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Cupon", "Cupon")
                        .WithMany("Usuarios")
                        .HasForeignKey("CuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Cupones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaCategoria", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Zonas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Zona", "Zona")
                        .WithMany("Categorias")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaPartida", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Partida", "Partida")
                        .WithMany("Zonas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.Zona", "Zona")
                        .WithMany("Partidas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaRonda", b =>
                {
                    b.HasOne("TPI2026.Dominio.Entidades.Ronda", "Ronda")
                        .WithMany("Zonas")
                        .HasForeignKey("RondaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI2026.Dominio.Entidades.ZonaPartida", "ZonaPartida")
                        .WithMany("Rondas")
                        .HasForeignKey("ZonaPartidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ronda");

                    b.Navigation("ZonaPartida");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.AperturaSobre", b =>
                {
                    b.Navigation("Cartas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Carta", b =>
                {
                    b.Navigation("Aperturas");

                    b.Navigation("CartasPartida");

                    b.Navigation("Colecciones");

                    b.Navigation("Habilidad");

                    b.Navigation("Mazos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Habilidades");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Coleccion", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Cupones");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Cupon", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Intercambio", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Monedas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.JugadorPartida", b =>
                {
                    b.Navigation("Cartas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Mazo", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Matchmakings");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Partida", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("Rondas");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Ronda", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Resultados");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Sobre", b =>
                {
                    b.Navigation("Aperturas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Cupones");

                    b.Navigation("Matchmakings");

                    b.Navigation("Mazos");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.Zona", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("TPI2026.Dominio.Entidades.ZonaPartida", b =>
                {
                    b.Navigation("Cartas");

                    b.Navigation("Resultados");

                    b.Navigation("Rondas");
                });
#pragma warning restore 612, 618
        }
    }
}
